Fix multiline parameter functions
raycast/extensions-swift-tools pull request #6
Opened 2024-04-14 16:29 UTC by SvenTiigi

This PR addresses a bug where a multiline parameter function causes a compile error.

<img width="857" alt="extensions-swift" src="https://github.com/raycast/extensions-swift-tools/assets/11733014/44230797-793a-43a0-b049-aa50b06e31ae">

It seems like that SwiftSyntax extracts the leading line break into the name of the variable which is then inserted in the generated macro which is then causing the compile error 🤔

The PR adds a simple ﻿`.trimmingCharacters(in: .whitespacesAndNewlines)` to any usage of the parameter/variable names since I didn't found a native SwiftSyntax solution for this problem 😅

2024-04-15 10:59 UTC, dehesa requested changes
Hey @SvenTiigi,

Thank you very much for the contribution and the test. We should have handled this case before.

As far as I understand `swift-syntax`, the `TokenSyntax`'s `text` property doesn't contain the "whitespace" trivia. Therefore you can call that and there is no need to add the `whitespaceAndNewlines` trimming functions.

I tried in my machine and it does work 😄 What do you think?

2024-04-15 10:59 UTC, dehesa commented on SwiftMacros/Implementation/RaycastMacro.swift
> +            "let \(raw: paramName): \(param.type)"
You could do this more succinctly:

```swift
"let \(raw: param.secondName?.text ?? param.firstName.text): \(param.type)"
```

2024-04-15 10:59 UTC, dehesa commented on SwiftMacros/Implementation/RaycastMacro.swift
> +              "\(raw: paramName) = try _argsDecoder.decode(\(param.type).self, from: cmdlineArgs[\(raw: i)])"
Similar thing here:

```swift
"\(raw: param.secondName?.text ?? param.firstName.text) = try _argsDecoder.decode(\(param.type).self, from: cmdlineArgs[\(raw: i)])"
```

2024-04-15 10:59 UTC, dehesa commented on SwiftMacros/Implementation/RaycastMacro.swift
> +                #"let _argError = _Ray.DecodingArgumentError(name: "\#(raw: paramName)", position: \#(raw: i), type: \#(param.type).self, data: cmdlineArgs[\#(raw: i)], underlying: error)"#
and here:

```swift
CatchClauseSyntax {
  #"let _argError = _Ray.DecodingArgumentError(name: "\#(raw: param.secondName?.text ?? param.firstName.text)", position: \#(raw: i), type: \#(param.type).self, data: cmdlineArgs[\#(raw: i)], underlying: error)"#
  "return callback.forward(error: _argError)"
}
```

2024-04-15 10:59 UTC, dehesa commented on SwiftMacros/Implementation/RaycastMacro.swift
> +                label: isWildCard ? .none : .init(stringLiteral: param.firstName.text.trimmingCharacters(in: .whitespacesAndNewlines)),
The label expression would be:

```swift
label: isWildCard ? .none : "\(raw: param.firstName.text)",
```

2024-04-15 10:59 UTC, dehesa commented on SwiftMacros/Implementation/RaycastMacro.swift
> +                expression: DeclReferenceExprSyntax(baseName: .identifier((param.secondName ?? param.firstName).text.trimmingCharacters(in: .whitespacesAndNewlines)))
This is unnecessary because the `text` doesn't include the "trivia".

2024-04-15 16:37 UTC, SvenTiigi commented
Looks good! Thanks for the hint! 😊
Much better than the manually String trimming 👌

2024-04-16 08:35 UTC, dehesa approved these changes

2024-04-16 08:35 UTC, merged